spring.application.name=ai-analysis-service
server.port=8082
openrouter.api.key= ${OPENROUTER_API_KEY}
openrouter.api.url= https://openrouter.ai/api/v1/chat/completions
openrouter.api.model= nvidia/nemotron-3-super-120b-a12b:free
slack.webhook.url = ${SLACK_WEBHOOK_URL}
jira.url=https://ghoshabhisek1988.atlassian.net
jira.email=ghosh.abhisek1988@gmail.com
jira.api-token=  ${JIRA_API_TOKEN}
jira.project-key=AM
