spring.application.name=log-ai-platform
opensearch.host.port=9200
alert.threshold = 1
alert.cooldown-seconds = 60
alert.scheduler-rate = 30000
alert.error-window-seconds = 240

openrouter.api.key= ${OPENROUTER_API_KEY}
openrouter.api.url= https://openrouter.ai/api/v1/chat/completions
openrouter.api.model= nvidia/nemotron-3-super-120b-a12b:free



